name: VM Stop Test

on:
  schedule:
    - cron: '5-59/10 * * * *'
  workflow_dispatch:

jobs:
  stop-vm:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          az vm deallocate \
            --resource-group forgeXdev \
            --name vmscheduletest
